package com.optimaxx.management.security.audit;

public enum AuditEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGIN_BLOCKED,
    TOKEN_REFRESHED,
    LOGOUT,
    PASSWORD_CHANGED,
    USER_CREATED,
    USER_ROLE_UPDATED,
    USER_STATUS_UPDATED,
    USER_SOFT_DELETED,
    DEVICE_SESSION_REVOKED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    TRANSACTION_TYPE_CREATED,
    TRANSACTION_TYPE_UPDATED,
    TRANSACTION_TYPE_DELETED,
    SALE_TRANSACTION_CREATED,
    CUSTOMER_CREATED,
    CUSTOMER_UPDATED,
    REPAIR_ORDER_CREATED,
    REPAIR_STATUS_UPDATED
}
